[project]
name = "pydantic-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hung Yip", email = "kwonghung.yip@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "geopy[aiohttp]>=2.5.0",
    "pydantic-ai>=2.47.0",
    "pydantic-ai-harness[playwright]>=0.34.0",
]

[project.scripts]
pydantic-agent = "pydantic_agent:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
